name: test

on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "macos", "windows"]
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      - if: ${{ matrix.os == 'windows' }}
        name: Setup MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      - run: ls ext
      - run: ls ext/raudio
      - run: ls ext/raudio/src
      - name: Build native extension (POSIX/MSVC)
        run: make -C ext
        env:
          MSYS_NO_PATHCONV: "1"
          MSYS2_ARG_CONV_EXCL: "*"
      - name: Run specs
        run: crystal spec --error-trace
  build_MinGW64:
    name: MinGW64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-crystal
            mingw-w64-x86_64-shards
            git
            make
      - name: Install dependencies
        shell: msys2 {0}
        run: shards install
      - name: Run tests
        shell: msys2 {0}
        run: |
          make -C ext
          crystal spec
